name: Auto Merge

permissions: {}

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]

jobs:
  auto-merge:
    if: |
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      (github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'github-actions[bot]')
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto Merge (will wait for required checks)
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr merge --repo "$GITHUB_REPOSITORY" --squash --auto --delete-branch "$PR_NUMBER"
